apiVersion: apps/v1
kind: Deployment
metadata:
  name: gvwsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gvwsa
  template:
    metadata:
      labels:
        app: gvwsa
    spec:
      containers:
      - image: okteto.dev/gvwsa:latest
        name: gvwsa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4bfca097-5e79-4d33-8901-dd9f0d6741ee"
        - name: Vless_Path
          value: "/vldgedgt827"
        - name: Vmess_UUID
          value: "4bfca097-5e79-4d33-8901-dd9f0d6741ee"
        - name: Vmess_Path
          value: "/vmeogu983hws"
        - name: Share_Path
          value: "/v2link"
